/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tw.cn.cap.gtb.todo;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.List;

class AppTest {
    @Test void should_list_existing_tasks() {
        List<String> result = new App().run();
        Assertions.assertEquals(List.of("1 caonishizhu"),result);
  }
}
