/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tw.cn.cap.gtb.todo;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.util.Arrays;
import java.util.List;

class AppTest {
    @Test void should_list_existing_tasks() throws IOException {
        List<String> result = new App().run();
        Assertions.assertEquals(Arrays.asList("1 caonishizhu"),result);
  }
}
